export default {
  NEW_CATEGORY: 'NEW_CATEGORY',
  UPDATE_CATEGORY: 'UPDATE_CATEGORY',
  REMOVE_CATEGORY: 'REMOVE_CATEGORY',
  NEW_LOCATION: 'NEW_LOCATION',
  UPDATE_LOCATION: 'UPDATE_LOCATION',
  REMOVE_LOCATION: 'REMOVE_LOCATION',
  LOCATIONS_VIEW: 'LOCATIONS_VIEW',
  CATEGORIES_VIEW: 'CATEGORIES_VIEW',
  ITEM_VIEW: 'ITEM_VIEW',
  NEW_ITEM_VIEW: 'NEW_ITEM_VIEW',
  CLOSE_ITEM_VIEW: 'CLOSE_ITEM_VIEW'
}