export default {
  CATEGORIES_VIEW: 'CATEGORIES_VIEW',
  NEW_CATEGORY: 'NEW_CATEGORY',
  UPDATE_CATEGORY: 'UPDATE_CATEGORY',
  REMOVE_CATEGORY: 'REMOVE_CATEGORY',
  LOCATIONS_VIEW: 'LOCATIONS_VIEW',
  NEW_LOCATION: 'NEW_LOCATION',
  UPDATE_LOCATION: 'UPDATE_LOCATION',
  REMOVE_LOCATION: 'REMOVE_LOCATION'
}